application: duluthredistrict
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: html/index.html
  upload: html/(.*)

- url: /current
  static_files: html/current.html
  upload: html/(.*)

- url: /proposal
  static_files: html/proposal.html
  upload: html/(.*)

- url: /all
  script: views.py

- url: /s/(.*)
  static_files: html/\1.html
  upload: html/(.*)
